'use client'

import { useState } from 'react'
import { Building2, Lock, Pencil, Plus } from 'lucide-react'
import { useAuth } from '@/lib/auth'
import { useCreateWorkHub, useUpdateWorkHub, useWorkHubs } from '@/hooks/useAdmin'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { FeedbackDialog } from '@/components/ui/FeedbackDialog'
import { Input } from '@/components/ui/Input'
import type { WorkHub } from '@/lib/types'

export default function WorkHubsPage() {
  const { user } = useAuth(); const { data: hubs = [], isLoading, isError, refetch } = useWorkHubs(user?.role === 'admin'); const create = useCreateWorkHub(); const update = useUpdateWorkHub()
  const [name, setName] = useState(''); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<WorkHub | null>(null); const [feedback, setFeedback] = useState<{ tone: 'success' | 'error'; message: string } | null>(null)
  if (user?.role !== 'admin') return <div className="page-padding mx-auto max-w-lg py-16 text-center"><Lock className="mx-auto mb-3 h-12 w-12 text-gray-400" /><p className="font-medium">สำหรับผู้ดูแลระบบเท่านั้น</p></div>
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!name.trim()) return; try { await create.mutateAsync({ name: name.trim() }); setName(''); setOpen(false); setFeedback({ tone: 'success', message: 'เพิ่ม WorkHub เรียบร้อยแล้ว' }) } catch { setFeedback({ tone: 'error', message: 'ไม่สามารถเพิ่ม WorkHub ได้' }) } }
  async function saveEdit(event: React.FormEvent) { event.preventDefault(); if (!editing || !name.trim()) return; try { await update.mutateAsync({ id: editing.id, name: name.trim() }); setEditing(null); setName(''); setFeedback({ tone: 'success', message: 'บันทึก WorkHub แล้ว' }) } catch { setFeedback({ tone: 'error', message: 'ไม่สามารถบันทึก WorkHub ได้' }) } }
  return <div className="page-padding mx-auto w-full max-w-none"><header className="mb-5 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-xl font-bold">WorkHub</h1><p className="mt-1 text-sm text-gray-600">จัดการโหนดระดับภูมิภาคที่ใช้จัดกลุ่มสำนักงาน</p></div><Button leftIcon={<Plus className="h-4 w-4" />} onClick={() => { setOpen((value) => !value); setEditing(null); setName('') }}>เพิ่ม WorkHub</Button></header>{(open || editing) && <Card className="mb-5"><form onSubmit={editing ? saveEdit : submit} className="flex max-w-xl gap-2"><Input label="ชื่อ WorkHub" required value={name} onChange={(event) => setName(event.target.value)} className="flex-1" /><div className="flex items-end gap-2"><Button type="submit" loading={create.isPending || update.isPending}>{editing ? 'บันทึกการแก้ไข' : 'บันทึก'}</Button><Button type="button" variant="outline" onClick={() => { setOpen(false); setEditing(null); setName('') }}>ยกเลิก</Button></div></form></Card>}<Card className="overflow-x-auto p-0">{isLoading ? <p className="p-6 text-sm text-gray-600">กำลังโหลด WorkHub…</p> : isError ? <div className="p-6"><p className="text-sm text-red-700">โหลดข้อมูลไม่สำเร็จ</p><Button className="mt-3" variant="outline" onClick={() => void refetch()}>ลองใหม่</Button></div> : hubs.length === 0 ? <p className="p-8 text-center text-sm text-gray-600">ยังไม่มี WorkHub</p> : <table className="min-w-[560px] w-full text-sm"><thead className="bg-gray-50 text-left text-gray-700"><tr><th className="px-4 py-3 font-semibold">WorkHub</th><th className="px-4 py-3 font-semibold">รหัส</th><th className="px-4 py-3 text-right font-semibold">การจัดการ</th></tr></thead><tbody>{hubs.map((hub) => <tr key={hub.id} className="border-t border-gray-100 hover:bg-gray-50"><td className="px-4 py-3 font-medium"><Building2 className="mr-2 inline h-4 w-4 text-pea-600" />{hub.name}</td><td className="px-4 py-3 font-mono text-xs text-gray-600">{hub.id}</td><td className="px-4 py-3 text-right"><Button size="sm" variant="outline" leftIcon={<Pencil className="h-3.5 w-3.5" />} onClick={() => { setEditing(hub); setName(hub.name); setOpen(false) }}>แก้ไข</Button></td></tr>)}</tbody></table>}</Card><p className="mt-3 text-sm text-gray-600">ไม่เปิด archive เพราะระบบยังต้องตรวจสอบสำนักงานที่อ้างอิง WorkHub ก่อน</p><FeedbackDialog open={Boolean(feedback)} tone={feedback?.tone ?? 'success'} title={feedback?.tone === 'error' ? 'ดำเนินการไม่สำเร็จ' : 'สำเร็จ'} message={feedback?.message ?? ''} onClose={() => setFeedback(null)} /></div>
}
